[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
bmp = "0.5.0"
dotenv = "0.15.0"
itertools = "0.13.0"
num = "0.4.3"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking", "rustls-tls"] }
