[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.12.9", features = ["blocking", "rustls-tls"] }

[lints.rust]
unused = "allow"
